services:
  src:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: src
    restart: always
    ports:
      - "8100:22367"
    volumes:
      - './src-config:/StarRailCopilot/config'
      - '/etc/localtime:/etc/localtime:ro'
  emulator:
    image: kylindemons/redroid:15.0.0_amd64-GApps-latest
    container_name: emulator
    restart: always
    stdin_open: true
    tty: true
    privileged: true
    ports:
      - "8101:5555"
    volumes:
      - ./redroid-data:/data
    command:
      - androidboot.redroid_width=720
      - androidboot.redroid_height=1280
      - androidboot.redroid_dpi=240
      - androidboot.redroid_fps=30
      - androidboot.redroid_gpu_mode=host 
      - ro.product.cpu.abilist0=x86_64,arm64-v8a,x86,armeabi-v7a,armeabi
      - ro.product.cpu.abilist64=x86_64,arm64-v8a
      - ro.product.cpu.abilist32=x86,armeabi-v7a,armeabi
      - ro.dalvik.vm.isa.arm=x86
      - ro.dalvik.vm.isa.arm64=x86_64
      - ro.enable.native.bridge.exec=1
      - ro.dalvik.vm.native.bridge=libndk_translation.so
      - ro.ndk_translation.version=0.2.2