services:
  src:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: src
    restart: always
    ports:
      - "8100:22367"
    volumes:
      - './src-config:/StarRailCopilot/config'
      - '/etc/localtime:/etc/localtime:ro'